# Generated by Django 4.1.7 on 2023-04-02 14:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Hackathon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, max_length=1000)),
                ("background_image", models.ImageField(upload_to="images/background")),
                ("hackathon_image", models.ImageField(upload_to="images/hackathon")),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "reward_prize",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "submission_type",
                    models.CharField(
                        choices=[
                            ("FILE", "File"),
                            ("IMAGE", "Image"),
                            ("LINK", "Link"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                ("summary", models.TextField(blank=True, max_length=1000)),
                (
                    "file_submission",
                    models.FileField(blank=True, upload_to="submissions/file/"),
                ),
                (
                    "image_submission",
                    models.ImageField(blank=True, upload_to="submissions/image/"),
                ),
                ("link_submission", models.URLField(blank=True)),
                (
                    "hackathon",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hackathonapp.hackathon",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
