# Generated by Django 4.1.7 on 2023-04-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hackathonapp", "0002_alter_submission_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hackathon",
            name="background_image",
            field=models.ImageField(
                default="default-background.jpg", upload_to="images/background"
            ),
        ),
        migrations.AlterField(
            model_name="hackathon",
            name="hackathon_image",
            field=models.ImageField(
                default="default-hackathon.jpg", upload_to="images/hackathon"
            ),
        ),
    ]
