# Generated by Django 4.1.7 on 2023-04-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hackathonapp", "0003_alter_hackathon_background_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hackathon",
            name="title",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
