# Generated by Django 4.1.7 on 2023-04-02 23:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("hackathonapp", "0005_alter_hackathon_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="hackathon",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
