# Generated by Django 4.1.7 on 2023-04-03 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hackathonapp", "0006_hackathon_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="hackathon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="hackathonapp.hackathon"
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="name",
            field=models.CharField(
                blank=True, default="Submission New", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="submission",
            constraint=models.UniqueConstraint(
                fields=("hackathon", "user"), name="single_submission_allowed"
            ),
        ),
    ]
