# Generated by Django 4.1.7 on 2023-04-03 02:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        (
            "hackathonapp",
            "0007_alter_submission_hackathon_alter_submission_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="updated_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
